# Generated by Django 4.0.5 on 2022-06-02 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_num', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.casestatus')),
            ],
        ),
        migrations.CreateModel(
            name='DocketFilers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.docket')),
            ],
        ),
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FilerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FilingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_index', models.IntegerField()),
                ('filed_on', models.DateTimeField(auto_now_add=True)),
                ('filer_url', models.CharField(max_length=100)),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.docket')),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filer')),
                ('filing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filingtype')),
            ],
        ),
        migrations.AddField(
            model_name='filer',
            name='filer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filertype'),
        ),
        migrations.AddField(
            model_name='filer',
            name='managing_dockets',
            field=models.ManyToManyField(related_name='managers', through='courtzapi.DocketFilers', to='courtzapi.docket'),
        ),
        migrations.AddField(
            model_name='filer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocketParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.docket')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filer')),
                ('party_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.partytype')),
            ],
        ),
        migrations.AddField(
            model_name='docketfilers',
            name='filer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filer'),
        ),
    ]
