# Generated by Django 4.0.5 on 2022-06-13 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_num', models.CharField(max_length=50)),
                ('case_name', models.CharField(default='tbd', max_length=300)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.casestatus')),
            ],
        ),
        migrations.CreateModel(
            name='Filer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FilerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FilingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RepFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.firm')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filer')),
            ],
        ),
        migrations.CreateModel(
            name='RepFirmParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filer')),
                ('rep_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.repfirm')),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='tbd', max_length=300)),
                ('docket_index', models.IntegerField()),
                ('filed_on', models.DateTimeField(auto_now_add=True)),
                ('file_pdf', models.FileField(default='', upload_to='caseFiles')),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='courtzapi.docket')),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filer')),
                ('filing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filingtype')),
            ],
        ),
        migrations.AddField(
            model_name='filer',
            name='filer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.filertype'),
        ),
        migrations.AddField(
            model_name='filer',
            name='firms',
            field=models.ManyToManyField(related_name='representatives', through='courtzapi.RepFirm', to='courtzapi.firm'),
        ),
        migrations.AddField(
            model_name='filer',
            name='representation',
            field=models.ManyToManyField(related_name='clients', through='courtzapi.RepFirmParty', to='courtzapi.repfirm'),
        ),
        migrations.AddField(
            model_name='filer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocketParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='courtzapi.docket')),
                ('party_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.partytype')),
                ('rep_firm_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courtzapi.repfirmparty')),
            ],
        ),
    ]
