# Generated by Django 4.0.5 on 2022-06-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filing',
            old_name='filer_url',
            new_name='file_url',
        ),
    ]
