# Generated by Django 4.0.5 on 2022-06-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0002_rename_filer_url_filing_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='docket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='courtzapi.docket'),
        ),
    ]
