# Generated by Django 4.0.5 on 2022-06-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0003_alter_filing_docket'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='case_name',
            field=models.CharField(default='tbd', max_length=300),
        ),
    ]
