# Generated by Django 4.0.5 on 2022-06-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0004_docket_case_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='title',
            field=models.CharField(default='tbd', max_length=300),
        ),
    ]
