# Generated by Django 4.0.5 on 2022-06-04 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0005_filing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docketparty',
            name='docket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='courtzapi.docket'),
        ),
    ]
