# Generated by Django 4.0.5 on 2022-06-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0006_alter_docketparty_docket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docket',
            old_name='completed_on',
            new_name='closed_on',
        ),
    ]
