# Generated by Django 4.0.5 on 2022-06-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtzapi', '0007_rename_completed_on_docket_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='file_pdf',
            field=models.FileField(default='', upload_to='caseFiles'),
        ),
    ]
